### ISSUE TITLE
Don't connect the form to the server socket

### ISSUE THREAD

**Issue by michaelnabil230** [laravel/reverb#78]
### Reverb Version

1.0@beta

### Laravel Version

v11.0.5

### PHP Version

8.3

### Description

I tried with the Postman and is connected well and returns the data and socket ID but javascript does not work I don't know where the issue

env file 

```env
APP_URL=https://reverb.test

BROADCAST_CONNECTION=reverb

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

REVERB_APP_ID=218623
REVERB_APP_KEY=laravel-key
REVERB_APP_SECRET=laravel-secret
REVERB_HOST="reverb.test"
REVERB_PORT=8080
REVERB_SCHEME=https

VITE_APP_NAME="${APP_NAME}"
VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

echo.js

```js
import Echo from 'laravel-echo';

import Pusher from 'pusher-js';
window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: 'reverb',
    key: import.meta.env.VITE_REVERB_APP_KEY,
    wsHost: import.meta.env.VITE_REVERB_HOST,
    wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
    wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
    enabledTransports: ['ws', 'wss'],
});

```

<img width="1409" alt="Screenshot 2024-03-13 at 9 25 55 PM" src="https://github.com/laravel/reverb/assets/46572405/b03b8da4-eb7c-4054-b473-58d2d5b93e51">

### Steps To Reproduce

...

**Comment by tarreislam** [comment]
where does `reverb.test` go? I suspect you want to type `localhost` or another hostname directing to an IP

**Comment by michaelnabil230** [comment]
When set in hostname localhost on the env, prints in the console error and doesn't connect

<img width="1693" alt="Screenshot 2024-03-13 at 9 38 16 PM" src="https://github.com/laravel/reverb/assets/46572405/892f6f70-6746-45e7-b725-e73b2337b2c3">

**Comment by joedixon** [comment]
If you don't have an SSL certificate for the domain (common for local development), you should set the `REVERB_SCHEME=http` rather than `https`. This will prevent Echo from connecting via secure WebSockets (wss).

**Comment by michaelnabil230** [comment]
I'm using Herd and the SSL is created by Herd

<img width="851" alt="Screenshot 2024-03-13 at 10 26 48 PM" src="https://github.com/laravel/reverb/assets/46572405/db5f22a3-1c70-4876-941b-41253fcaf3b8">

**Comment by joedixon** [comment]
If you start the server with the `--debug` option, do you see the connection attempt?

**Comment by michaelnabil230** [comment]
It does not print anything

**Comment by michaelnabil230** [comment]
Is printing after 3 times failed a request from echo

<img width="1713" alt="Screenshot 2024-03-13 at 11 05 08 PM" src="https://github.com/laravel/reverb/assets/46572405/f7ba90fb-d572-4288-b734-39e0dbca25af">
<img width="964" alt="Screenshot 2024-03-13 at 11 04 58 PM" src="https://github.com/laravel/reverb/assets/46572405/274edc38-56f8-4e74-b019-f1fdb658390c">

**Comment by aj-norman** [comment]
+1 here - Not to sure if this helps, but I have the same error on Safari as well

`[Error] WebSocket connection to 'wss://0.0.0.0:8080/app/laravel-herd?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: bad URL` 

I'm using Herd Pro to manage the reverb service. My config used for reverb is as show in the Herd Pro screenshot, and the error occurs regardless if `REVERB_SCHEME` is set to `http` or `https`

My steps to reproduce
- Create new L11 project via Herd
- Create Reverb service via Herd
- run `artisan broadcasting:install`, install deps and use Reverb
- import `@vite` directive into `welcome.blade.php`

<img width="1022" alt="Screenshot 2024-03-13 at 22 00 00" src="https://github.com/laravel/reverb/assets/24577267/cba609d2-5027-4a70-816a-8b9155733d03">

**Comment by fylzero** [comment]
+1 here as well. Same issue - Herd Pro, using reverb service, with SSL (via Herd)...

```
REVERB_APP_ID=1001
REVERB_APP_KEY=laravel-herd
REVERB_APP_SECRET=secret
REVERB_HOST="demoapp.test" // Using the name of the project as it says in the Herd instructions
REVERB_PORT=8080
// REVERB_SCHEME defaults to https so leaving that unset
```

**Comment by fylzero** [comment]
Turning off SSL in Herd, changing the APP_URL to http..., and updating the .env settings for Reverb:

```
REVERB_APP_ID=1001
REVERB_APP_KEY=laravel-herd
REVERB_APP_SECRET=secret
REVERB_HOST="0.0.0.0"
# REVERB_HOST="deskninja.test"
REVERB_PORT=8080
REVERB_SCHEME=http
```

Got this working locally. Likely an issue with the SSL. I saw in the docs you could target the SSL cert by entering it in the settings, going to mess around and see if that fixes it.

**Comment by aj-norman** [comment]
I can confirm @fylzero findings - Removing SSL on Herd does seem to fix the issue and allows a Reverb connection.

Using SSL is a different story. I can get a connection with the following below with SSL switched on in Herd, however it seems to disconnect after 30ish seconds with the same `WebSocket connection to 'wss://0.0.0.0:8080...' failed: bad URL`

```env
APP_URL=https://reverb-test.test

REVERB_APP_ID=1001
REVERB_APP_KEY=laravel-herd
REVERB_APP_SECRET=secret
REVERB_HOST="reverb-test.test"
REVERB_PORT=8080
REVERB_SCHEME=https     # Force TLS
```

**Comment by joedixon** [comment]
I just ran through the SSL setup with the following steps and am able to connect (FF, Safari and Chrome) with no issues over wss using the following steps:

- Install Laravel 11 app (reverb-ssl available at `reverb-ssl.test`)
- Secure with Herd
- Install broadcasting `php artisan install:broadcasting`
- Update `REVERB_HOST=reverb-ssl.test` in my environment
- Rebuild assets

Reverb lets me know I'm starting a secure server:

<img width="665" alt="Screenshot 2024-03-14 at 14 54 38" src="https://github.com/laravel/reverb/assets/3438564/da394fed-abbf-4b69-a6e1-a7f1e9a0f43e">

And I'm able to connect:

<img width="491" alt="Screenshot 2024-03-14 at 14 48 05" src="https://github.com/laravel/reverb/assets/3438564/7ecdd7ca-14c6-4147-bbec-906840dbd97a">

<img width="554" alt="Screenshot 2024-03-14 at 14 55 28" src="https://github.com/laravel/reverb/assets/3438564/aedeec87-1ece-4aaa-9fdc-496f500412e4">

@aj-norman, if you're seeing Echo trying to connect to 0.0.0.0, it's likely you either haven't rebuilt your frontend since updating `REVERB_HOST` or your `VITE_REVERB_HOST` variable hasn't been updated.

@fylzero The built-in Reverb service doesn't have SSL support (yet).

**Comment by lsdevelop** [comment]
I believe it must be something in the migration from Laravel 10 to 11, I had 10 with laravel websockets running fine, but after the update I'm no longer able to do so.

> I just ran through the SSL setup with the following steps and am able to connect (FF, Safari and Chrome) with no issues over wss using the following steps:
> 
> * Install Laravel 11 app (reverb-ssl available at `reverb-ssl.test`)
> * Secure with Herd
> * Install broadcasting `php artisan install:broadcasting`
> * Update `REVERB_HOST=reverb-ssl.test` in my environment
> * Rebuild assets
> 
> Reverb lets me know I'm starting a secure server:
> 
> <img alt="Screenshot 2024-03-14 at 14 54 38" width="665" src="https://private-user-images.githubusercontent.com/3438564/312887165-da394fed-abbf-4b69-a6e1-a7f1e9a0f43e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0Mjk2MTYsIm5iZiI6MTcxMDQyOTMxNiwicGF0aCI6Ii8zNDM4NTY0LzMxMjg4NzE2NS1kYTM5NGZlZC1hYmJmLTRiNjktYTZlMS1hN2YxZTlhMGY0M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTUxNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYxYmI3NWQ4OTQ1M2Y3OWZhMmJkNzI0ZThjZjliYmUwNWQ5ZjE5YWU2Y2M4ZWM5ZmE4YTQxYTk5OWU4NjFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yjfJhJ-YeEEwxHYMj6BWKO7suXQTYxmhVQkwsUbdyZ4">
> And I'm able to connect:
> 
> <img alt="Screenshot 2024-03-14 at 14 48 05" width="491" src="https://private-user-images.githubusercontent.com/3438564/312887325-7ecdd7ca-14c6-4147-bbec-906840dbd97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0Mjk2MTYsIm5iZiI6MTcxMDQyOTMxNiwicGF0aCI6Ii8zNDM4NTY0LzMxMjg4NzMyNS03ZWNkZDdjYS0xNGM2LTQxNDctYmJlYy05MDY4NDBkYmQ5N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTUxNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ5YjAxZmJkNzUwN2FjNGI4Y2QxNWNhOGRmZDE5YTg2MGE4M2M2MGVkMGQ4ZGI3N2Q2MDg2OWQ2NzA4NTBjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qtmIGKRTsJ9HvZloNEGmFO0o2D4ogkhwOXGvf42qzMw"> <img alt="Screenshot 2024-03-14 at 14 55 28" width="554" src="https://private-user-images.githubusercontent.com/3438564/312887515-aedeec87-1ece-4aaa-9fdc-496f500412e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0Mjk2MTYsIm5iZiI6MTcxMDQyOTMxNiwicGF0aCI6Ii8zNDM4NTY0LzMxMjg4NzUxNS1hZWRlZWM4Ny0xZWNlLTRhYWEtOWZkYy00OTZmNTAwNDEyZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTUxNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk4N2JhMmNiNTYyN2Q5ZmRjN2U1MWQxOTU3YjlmMjc5Y2QwMjUxOTJhNTJlZWUxMTY3OWYxMjM4N2Y5YmQzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HBBcNxW1UONVlV_Ll6GXM0N7_kus753HWrx4Wu19mtA">
> @aj-norman, if you're seeing Echo trying to connect to 0.0.0.0, it's likely you either haven't rebuilt your frontend since updating `REVERB_HOST` or your `VITE_REVERB_HOST` variable hasn't been updated.
> 
> @fylzero The built-in Reverb service doesn't have SSL support (yet).

**Comment by lsdevelop** [comment]
in my tests, run npm run dev "vite dev" the connection of websockets return success but in vite port
![image](https://github.com/laravel/reverb/assets/62124151/e84f1d8f-c00a-433b-8e31-bb205e4607bb)
after build assets, not return error and connection more.

**Comment by aj-norman** [comment]
@joedixon - Apologies, I should have made it clearer above - I changed the `0.0.0.0` to my `reverb-test.test` domain and that worked on a `http` connection, but SSL still has issues when trying `https`. However I think you've cleared it up with the following statement above

> The built-in Reverb service doesn't have SSL support (yet).

**Comment by lsdevelop** [comment]
> > in my tests, run npm run dev "vite dev" the connection of websockets return success but in vite port
> 
> 
> 
> @lsdevelop that's not the Reverb socket server, that's part of the Vite dev server which is why you don't see it after building your assets for production.

Yeah, my fucking stupidity

**Comment by joedixon** [comment]
So is your issue resolved now @lsdevelop?

**Comment by lsdevelop** [comment]
> So is your issue resolved now @lsdevelop?

Nope, I'm start trying create new laravel project with broadcasting to validate my migrated files (10 with laravel websockets to 11 with reverb)

**Comment by joedixon** [comment]
Made some changes here: https://github.com/laravel/reverb/pull/87/files

Could you give that branch a try and set your desired `max_request_size` value in config / env?

**Comment by fylzero** [comment]
It sounds to me like this is an issue with Herd not supporting SSL for their Reverb service. Maybe this is also the cause of the Safari issue? Going to experiment more today.

**Comment by fylzero** [comment]
@lsdevelop I can say that I do not believe this is related to the upgrade. I did a diff check on a fresh project and made sure everything was setup the same as a new project. That said, when I upgraded, it did not add the broadcast config for Reverb....but this did not resolve my issue.

@joedixon Can you share the Reverb start command you used for SSL? Did you just run `php artisan reverb:start` or was it more than that?

**Comment by joedixon** [comment]
@fylzero just `php artisan reverb:start`, but you need to ensure `REVERB_HOSTNAME` is set to a domain served by Herd and that domain must be secured by Herd. Reverb will detect the rest.

**Comment by fylzero** [comment]
@joedixon I just tried this and Reverb does not work this way. I'm a bit confused, in Herd when using the Reverb service, it provides the REVERB_APP_ID, REVERB_APP_KEY, and REVERB_APP_SECRET. When removing the Herd Reverb service and using `php artisan reverb:start` how do we/does it know what these values should be?

Currently:
```
REVERB_APP_ID=1001
REVERB_APP_KEY=laravel-herd
REVERB_APP_SECRET=secret
REVERB_HOST="myapp.test"
REVERB_PORT=8080
REVERB_SCHEME=https
```

**Comment by lsdevelop** [comment]
> @lsdevelop I can say that I do not believe this is related to the upgrade. I did a diff check on a fresh project and made sure everything was setup the same as a new project. That said, when I upgraded, it did not add the broadcast config for Reverb....but this did not resolve my issue.
> 
> Note: The upgrade/broadcast config issue was just resolved here - #84
> 
> @joedixon Can you share the Reverb start command you used for SSL? Did you just run `php artisan reverb:start` or was it more than that?

After update broadcast.php, the connection has return this, i`m continue trying.
![image](https://github.com/laravel/reverb/assets/62124151/6f71098b-49bf-448a-ad76-95506eb3daf6)

**Comment by joedixon** [comment]
> @joedixon I just tried this and Reverb does not work this way. I'm a bit confused, in Herd when using the Reverb service, it provides the REVERB_APP_ID, REVERB_APP_KEY, and REVERB_APP_SECRET. When removing the Herd Reverb service and using `php artisan reverb:start` how do we/does it know what these values should be?
> 
> Currently:
> 
> ```
> REVERB_APP_ID=1001
> REVERB_APP_KEY=laravel-herd
> REVERB_APP_SECRET=secret
> REVERB_HOST="myapp.test"
> REVERB_PORT=8080
> REVERB_SCHEME=https
> ```
> 
> Also, I think about you meant `REVERB_HOST` as `REVERB_HOSTNAME` is not referenced in any configs - though the config key is hostname.
> 
> I've opened a bug with Herd: [beyondcode/herd-community#467](https://github.com/beyondcode/herd-community/issues/467)

I'm not sure it's a bug with Herd, it's just not supported on the built-in service yet.

The app key, id and secret can be anything, but if you remove them all from your .env and run `reverb:install`, they will be populated for you.

**Comment by fylzero** [comment]
@joedixon Apologies. I'm not sure I understand the difference between Herd's Reverb service and the built-in service. Can you clarify that?

Also, that's great those can be anything. Then do you have any thoughts as to why this isn't working for me with the reverb:start command?

Thanks!

**Comment by joedixon** [comment]
Herd's service is completely separate from your application. It's essentially a standalone Laravel application running Reverb which any of your own applications can connect to. It's really for use in scenarios where you want to use Reverb, but not have it running alongside your application.

What's the error you're seeing when trying to start the server with `reverb:start`?

**Comment by fylzero** [comment]
@joedixon Ok, so - using the Herd Reverb service without SSL, everything with Reverb works.

If I...
- Turn ON the SSL in Herd for the site
- Set APP_URL=https... in .env
- Change REVERB_SCHEME=https in .env
- Stop and remove the Reverb service from Herd
- Then run `php artisan reverb:start`

I get the error:
WebSocket connection to 'wss://myapp.test:8080/app/laravel-herd?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: 

...and the websocket event does nothing. No other errors.

**Comment by joedixon** [comment]
What is displayed in the console after running the reverb:start command?

**Comment by fylzero** [comment]
@joedixon 

INFO  Starting secure server on 0.0.0.0:8080 (myapp.test).

**Comment by joedixon** [comment]
Can you use the --debug option when starting the command to see if any connection events are being sent to the server?

**Comment by fylzero** [comment]
@joedixon Nothing more is outputting there - and as I mentioned, the browser console shows connection failed.

I do see (after a second or two):
Pruning Stale Connections ........................................................................................................................
Pinging Inactive Connections .....................................................................................................................

**Comment by joedixon** [comment]
Ok, if you hit https://myapp.test:8080/app/laravel-herd in the browser, do you get an SSL error or a server error?

**Comment by fylzero** [comment]
@joedixon Says "Internal server error"

**Comment by joedixon** [comment]
Can you share all of your `REVERB_` and `VITE_REVERB_` prefixed environment variables and your echo configuration?

**Comment by fylzero** [comment]
@joedixon 

```
REVERB_APP_ID=1001
REVERB_APP_KEY=laravel-herd
REVERB_APP_SECRET=secret
REVERB_HOST="myapp.test"
REVERB_PORT=8080
REVERB_SCHEME=https

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

**Comment by fylzero** [comment]
@joedixon Existing/upgraded app. Testing in Brave (shields off - basically Chrome). I'm not seeing any errors that haven't been shared already.

I put the Echo code directly in my app.js:

```javascript
// Echo
import Echo from 'laravel-echo'

import Pusher from 'pusher-js'
window.Pusher = Pusher

window.Echo = new Echo({
    broadcaster: 'reverb',
    key: import.meta.env.VITE_REVERB_APP_KEY,
    wsHost: import.meta.env.VITE_REVERB_HOST,
    wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
    wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
    enabledTransports: ['ws', 'wss'],
})
```

My vue code:
```javascript
onMounted(() => {
    Echo.private(`branch.${page.props.authUser.branch_id}`).listen('IssueCreatedEvent', (event) => {
        router.reload({ only: ['issues'] })
    })
})

onUnmounted(() => {
    Echo.leave(`branch.${page.props.authUser.branch_id}`)
})
```

I mean this all works without SSL - so I don't think anything is misconfigured. If youre open to it, we can jump on a Google Meet or something to walk through this. My email is just my github username at gmail dot com. I just had ankle surgery so I'm laid up with a laptop and nothing to do. Really appreciate your help here!

**Comment by lsdevelop** [comment]
Really, non secure working fine, tomorrow i deploy to my staging environment with reverb and ssl to starting tests in similarly production environment

**Comment by joedixon** [comment]
@fylzero can you try a brand new project just so we can rule out anything specific to the project / host?

**Comment by fylzero** [comment]
@joedixon Will do. ...but I've already doff checked to make sure nothing was missing compared to a fresh project. Also, the fact that it works sans-SSL should I think rule that out as an issue.

**Comment by lsdevelop** [comment]
Update, in production, works fine with SSL, the problem is local and specify from herd/valet.

**Comment by trydalcoholic** [comment]
Hi @joedixon!
I have a similar problem. At first I tried to connect Reverb on the current project, but I got the error `WebSocket connection to...` in the browser console.
Then I did a clean install of Laravel using docker in a WSL environment. And I still get the same error: `WebSocket connection to 'ws://localhost:8080/app/vorzsu5irbdva48qipku?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: `

![image](https://github.com/laravel/reverb/assets/20430159/93632def-7536-49fe-b8a5-3cc15ae410a8)

**sail artisan reverb:start --debug:** 
```
INFO  Starting server on 0.0.0.0:8080 (localhost).

Pruning Stale Connections ...................................................................  
Pinging Inactive Connections ................................................................  
Pruning Stale Connections ...................................................................  
Pinging Inactive Connections ................................................................  
```

**.env:**
```
APP_URL=http://localhost

BROADCAST_CONNECTION=reverb

REVERB_APP_ID=222435
REVERB_APP_KEY=vorzsu5irbdva48qipku
REVERB_APP_SECRET=uig8whxhdpkafmocbn4u
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

**echo.js:**
```js
import Echo from 'laravel-echo';

import Pusher from 'pusher-js';
window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: 'reverb',
    key: import.meta.env.VITE_REVERB_APP_KEY,
    wsHost: import.meta.env.VITE_REVERB_HOST,
    wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
    wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
    enabledTransports: ['ws', 'wss'],
});
```

I use WSL and Laravel Sail. The server is started using the command `sail artisan serve`

**Comment by Cloner311** [comment]
I have exactly the same problem

Web server: Lightspeed
Laravel: version 11

error : 

`app-CamLVODr.js:13 WebSocket connection to 'wss://mydomain.com/app/cmjnsrygmqfjkdrsmxib?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: `

**Comment by pratikkuikel** [comment]
I am facing the same issue, 

Server Config : 
![image](https://github.com/laravel/reverb/assets/35728183/eeb39666-9a17-42bc-970d-9b7e429a841a)

Echo : 
![image](https://github.com/laravel/reverb/assets/35728183/f2ddc240-9724-4380-8f8b-5fd9fd17bb2f)

Client side Implementation: 
![image](https://github.com/laravel/reverb/assets/35728183/8a826562-578d-4913-b37b-c2e9bdc8a7d9)


Console errors in the browser : 
![image](https://github.com/laravel/reverb/assets/35728183/1b692ce0-cab3-4f54-9585-d2ad378fa6fd)

Network Tab : 
![image](https://github.com/laravel/reverb/assets/35728183/169cd518-8c7d-43c4-bae2-650ffe8d4505)
![image](https://github.com/laravel/reverb/assets/35728183/569d8926-187b-45b1-b40b-6a7d341c66a1)
![image](https://github.com/laravel/reverb/assets/35728183/822987af-cf40-48d9-ae15-11c3dc380c1f)


And the connection is being established in reverb debug terminal : 
![image](https://github.com/laravel/reverb/assets/35728183/3d48b93e-66f9-4e7c-885d-0d6728cb2666)

**Comment by pilutiful** [comment]
> sail

I also encountered this problem using Sail. Windows, WSL, Laravel Sail. Laravel 10 upgraded to 11.

I had to include port 8080 (used by Reverb) in docker-compose.yml - now working perfectly!

<img width="909" alt="Udklip" src="https://github.com/laravel/reverb/assets/72547351/cc965662-8de2-4592-84e7-b5b819fdc5a8">

**Comment by pilutiful** [comment]
> Hi @joedixon! I have a similar problem. At first I tried to connect Reverb on the current project, but I got the error `WebSocket connection to...` in the browser console. Then I did a clean install of Laravel using docker in a WSL environment. And I still get the same error: `WebSocket connection to 'ws://localhost:8080/app/vorzsu5irbdva48qipku?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: `
> 
> ![image](https://private-user-images.githubusercontent.com/20430159/313429850-93632def-7536-49fe-b8a5-3cc15ae410a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTg2MTAsIm5iZiI6MTcxMDY5ODMxMCwicGF0aCI6Ii8yMDQzMDE1OS8zMTM0Mjk4NTAtOTM2MzJkZWYtNzUzNi00OWZlLWI4YTUtM2NjMTVhZTQxMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE3NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMjc1NzQ2ZTFmNTVhYTc1OThlZDU2YzBjZTQwOTQzNjQ4ZDY3MWY0NzZjN2RkMDg4ZTljYmY1OGM2ZjdkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ul0BRSc2WDoLCaux24GCVQ68sQmcVA7Vyr4Vq3R9JkQ)
> 
> **sail artisan reverb:start --debug:**
> 
> ```
> INFO  Starting server on 0.0.0.0:8080 (localhost).
> 
> Pruning Stale Connections ...................................................................  
> Pinging Inactive Connections ................................................................  
> Pruning Stale Connections ...................................................................  
> Pinging Inactive Connections ................................................................  
> ```
> 
> **.env:**
> 
> ```
> APP_URL=http://localhost
> 
> BROADCAST_CONNECTION=reverb
> 
> REVERB_APP_ID=222435
> REVERB_APP_KEY=vorzsu5irbdva48qipku
> REVERB_APP_SECRET=uig8whxhdpkafmocbn4u
> REVERB_HOST="localhost"
> REVERB_PORT=8080
> REVERB_SCHEME=http
> 
> VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
> VITE_REVERB_HOST="${REVERB_HOST}"
> VITE_REVERB_PORT="${REVERB_PORT}"
> VITE_REVERB_SCHEME="${REVERB_SCHEME}"
> ```
> 
> **echo.js:**
> 
> ```js
> import Echo from 'laravel-echo';
> 
> import Pusher from 'pusher-js';
> window.Pusher = Pusher;
> 
> window.Echo = new Echo({
>     broadcaster: 'reverb',
>     key: import.meta.env.VITE_REVERB_APP_KEY,
>     wsHost: import.meta.env.VITE_REVERB_HOST,
>     wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
>     wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
>     forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
>     enabledTransports: ['ws', 'wss'],
> });
> ```
> 
> I use WSL and Laravel Sail. The server is started using the command `sail artisan serve`

I also encountered this problem using Sail. Windows, WSL, Laravel Sail. Laravel 10 upgraded to 11.

I had to include port 8080 (used by Reverb) in docker-compose.yml - now working perfectly!

<img width="909" alt="Udklip" src="https://github.com/laravel/reverb/assets/72547351/0bae9f14-e9ad-4202-a28b-95d353330630">

**Comment by pilutiful** [comment]
> Hi @joedixon! I have a similar problem. At first I tried to connect Reverb on the current project, but I got the error `WebSocket connection to...` in the browser console. Then I did a clean install of Laravel using docker in a WSL environment. And I still get the same error: `WebSocket connection to 'ws://localhost:8080/app/vorzsu5irbdva48qipku?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: `
> 
> ![image](https://private-user-images.githubusercontent.com/20430159/313429850-93632def-7536-49fe-b8a5-3cc15ae410a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTg2MTAsIm5iZiI6MTcxMDY5ODMxMCwicGF0aCI6Ii8yMDQzMDE1OS8zMTM0Mjk4NTAtOTM2MzJkZWYtNzUzNi00OWZlLWI4YTUtM2NjMTVhZTQxMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE3NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMjc1NzQ2ZTFmNTVhYTc1OThlZDU2YzBjZTQwOTQzNjQ4ZDY3MWY0NzZjN2RkMDg4ZTljYmY1OGM2ZjdkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ul0BRSc2WDoLCaux24GCVQ68sQmcVA7Vyr4Vq3R9JkQ)
> 
> **sail artisan reverb:start --debug:**
> 
> ```
> INFO  Starting server on 0.0.0.0:8080 (localhost).
> 
> Pruning Stale Connections ...................................................................  
> Pinging Inactive Connections ................................................................  
> Pruning Stale Connections ...................................................................  
> Pinging Inactive Connections ................................................................  
> ```
> 
> **.env:**
> 
> ```
> APP_URL=http://localhost
> 
> BROADCAST_CONNECTION=reverb
> 
> REVERB_APP_ID=222435
> REVERB_APP_KEY=vorzsu5irbdva48qipku
> REVERB_APP_SECRET=uig8whxhdpkafmocbn4u
> REVERB_HOST="localhost"
> REVERB_PORT=8080
> REVERB_SCHEME=http
> 
> VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
> VITE_REVERB_HOST="${REVERB_HOST}"
> VITE_REVERB_PORT="${REVERB_PORT}"
> VITE_REVERB_SCHEME="${REVERB_SCHEME}"
> ```
> 
> **echo.js:**
> 
> ```js
> import Echo from 'laravel-echo';
> 
> import Pusher from 'pusher-js';
> window.Pusher = Pusher;
> 
> window.Echo = new Echo({
>     broadcaster: 'reverb',
>     key: import.meta.env.VITE_REVERB_APP_KEY,
>     wsHost: import.meta.env.VITE_REVERB_HOST,
>     wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
>     wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
>     forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
>     enabledTransports: ['ws', 'wss'],
> });
> ```
> 
> I use WSL and Laravel Sail. The server is started using the command `sail artisan serve`

I also encountered this using Laravel Sail (Windows, WSL, Laravel 10 upgraded to 11).

By added port 8080 (used by Reverb) to docker-compose.yml solved the problem.

<img width="909" alt="Udklip" src="https://github.com/laravel/reverb/assets/72547351/123302b9-b65d-4e79-8e91-29ba5446816c">

**Comment by trydalcoholic** [comment]
@pilutiful 
That's great! It really works now. Thank you very much!

**Comment by joedixon** [comment]
Closing this now as we have a few different problems merged into the same issue. If you are still running into a problem, please open a new issue.

**Comment by ritwikBiswas007** [comment]
cluster: 'Redis', 

Add this line in your Echo options

**Comment by tester-rr** [comment]
i have been following the conversation but it seems am still facing the same challenge:
am not using docker or herd; for ssl certificate i used certbot to generate the ssl certifice and my site is working just fine for https; could please help;
this is the error that am logging in my laravel 11 project;
[2024-08-28 14:26:26] local.ERROR: Pusher error: cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://eriex.darth.cloud:8080/apps/997772/events?auth_key=3fulvzenpsefbebv0b8q&auth_timestamp=1724855176&auth_version=1.0&body_md5=a7134a0c1092a1ed097ba993627c8cb7&auth_signature=bfec7daea5c21cf543e84ec49217f0f9cd596c59e4cc55dafeb93819c8fec5e9. {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://eriex.darth.cloud:8080/apps/997772/events?auth_key=3fulvzenpsefbebv0b8q&auth_timestamp=1724855176&auth_version=1.0&body_md5=a7134a0c1092a1ed097ba993627c8cb7&auth_signature=bfec7daea5c21cf543e84ec49217f0f9cd596c59e4cc55dafeb93819c8fec5e9. at /var/www/Zambezi-Solutions/payment-system/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:164)
[stacktrace]
#0 /var/www/Zambezi-Solutions/payment-system/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(92): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
#1



then my env file configuration;
REVERB_APP_ID=997772
REVERB_APP_KEY=3fulvzenpsefbebv0b8q
REVERB_APP_SECRET=gi4uxcnqe5zdj6zp3yhc
REVERB_HOST="eriex.darth.cloud"
REVERB_PORT=8080
REVERB_SCHEME=https
#REVERB_SERVER_HOST=49.13.226.0
#REVERB_SERVER_PORT=8080


then my reverb.php file
 'servers' => [

        'reverb' => [
            'host' => env('REVERB_SERVER_HOST', '0.0.0.0'),
            'port' => env('REVERB_SERVER_PORT', 8080),
            'hostname' => env('REVERB_HOST'),
            'options' => [
                'tls' => [
                    'cert' => '/etc/letsencrypt/live/eriex.darth.cloud/fullchain.pem',
                    'key' => '/etc/letsencrypt/live/eriex.darth.cloud/privkey.pem',
                ],
            ],



then my echo.js is
import Echo from 'laravel-echo';

import Pusher from 'pusher-js';
window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: 'reverb',
    key: import.meta.env.VITE_REVERB_APP_KEY,
    wsHost: import.meta.env.VITE_REVERB_HOST,
    wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
    wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
    enabledTransports: ['ws', 'wss'],
});

**Comment by peligro** [comment]
hola, lo resolví de la siguiente forma:

agregué la IP en la variable: 

REVERB_HOST="192.168.1.88"

y reconstruí con npm un build para que tome los cambios.

Funcionó perfecto!!! incluso lo probé de otros equipos conectados a la misma red de manera exitosa.

Saludos desde Viña del Mar, Chile

**Comment by Silomalo** [comment]
> Update, in production, works fine with SSL, the problem is local and specify from herd/valet.

No, getting error:
WebSocket connection to 'wss://domain.com:8080/app/hoxt1tdbscobu52wqeqf?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: WebSocket is closed before the connection is established.

**Comment by SeyamMs** [comment]
well I faced this problem as well and this helped me, consider taking a look here
https://gist.github.com/maxkostinevich/97c9e14f9b4ab8076582de9912e6524d

**Comment by Invsqa** [comment]
Check this

https://medium.com/@amolakh10/websocket-laravel-11-reverb-secure-https-private-on-local-machine-example-of-one-to-one-chat-ffede3a26900
